CREATE TABLE volunteer(
    VOLUNTEER_ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(50) NOT NULL,
    LAST_NAME varchar(50) NOT NULL,
    PASSWORD varchar(50) NOT NULL,
    PRIMARY KEY (VOLUNTEER_ID)
);

CREATE TABLE organization(
    ORGANIZATION_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE project(
    PROJECT_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    HOURS INT NOT NULL,
    ORGANIZATION_ID INT NOT NULL,
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES organization(ORGANIZATION_ID),
    PRIMARY KEY (PROJECT_ID)
);

CREATE TABLE requst(
    REQUEST_ID INT NOT NULL AUTO_INCREMENT,
    REQUEST_INFO VARCHAR(50) NOT NULL,
    HOURS INT NOT NULL,
    APPROVED BOOL,
    VOLUNTEER_ID INT NOT NULL,
    PROJECT_ID INT NOT NULL,
    FOREIGN KEY (VOLUNTEER_ID) REFERENCES volunteer(VOLUNTEER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(PROJECT_ID),
    PRIMARY KEY (REQUEST_ID)
);

